export default {
  user: {
    getUserList: "/user/getUserList",
    getUserListByID: "/user/getUserListByID",
    register: "/user/register",
    login: "/user/login",
    removeById: "/user/removeById",
    modifyById: "/user/modifyById",
    getUserById: "/user/getUserById",
  },
  tree: {
    getTreeById: "/tree/getTreeById",
    getTreeList: "/tree/getTreeList",
    getTreeListByUserID: "/tree/getTreeListByUserID",
    getTreeListByID: "/tree/getTreeListByID",
    addTree: "/tree/addTree",
    removeById: "/tree/removeById",
    modifyById: "/tree/modifyById",
  },
  uploadCenter: {
    upload: "/uploadCenter/upload",
    files: "/uploadCenter/files",
  },
  record: {
    getRecordByUserID: "/record/getRecordByUserID",
    modifyRecordUser: "/record/modifyRecordUser",
    modifyRecordTree: "/record/modifyRecordTree",
    modifyRecordOrder: "/record/modifyRecordOrder",
    modifyByID: "/record/modifyByID",
  },
  order: {
    getOrderList: "/order/getOrderList",
    getOrderListByID: "/order/getOrderListByID",
    addOrder: "/order/addOrder",
    removeById: "/order/removeById",
    modifyById: "/order/modifyById",
    getOrderListByUserID: "/order/getOrderListByUserID",
    getOrderByTreeID: "/order/getOrderByTreeID",
    modifyByTreeID: "/order/modifyByTreeID",
  },
  socket: {
    addSocket: "/socket/addSocket",
    removeById: "/socket/removeById",
    modifyById: "/socket/modifyById",
    getSocketByUserID: "/socket/getSocketByUserID",
  },
  alipay: {
    pagePay: "/alipay/pagePay",
    refund: "/alipay/refund",
    query: "/alipay/query",
  },
  comment: {
    getCommentByTreeID: "/comment/getCommentByTreeID",
    removeById: "/comment/removeById",
    addComment: "/comment/addComment",
  },
};
